M48
; DRILL file {KiCad (6.0.10-0)} date Friday, February 17, 2023 at 09:14:47 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T09:14:47-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.2Y-3.5
X5.4Y-3.5
X5.5Y-3.5
X5.8Y-3.4
X5.8Y-3.8
X5.9942Y-3.6058
X6.0Y-3.1
X6.0Y-3.7
X6.0Y-3.8
X6.1Y-3.6
X6.3Y-3.7
T2
X5.6075Y-3.1598
X5.8075Y-3.1598
T0
M30
